spring:
  application:
    name: store-gateway

  cloud:
    discovery:
      locator:
        enabled: true
    gateway:
      routes:
        - id: store-auth
          uri: lb://store-auth
          predicates:
            - Path=/auth/**

        - id: store-account
          uri: lb://store-account
          predicates:
            - Path=/accounts/**
        
        - id: store-winrecord
          uri: lb://store-winrecord
          predicates:
            - Path=/winrecord/**

        - id: store-tournamentmanager
          uri: lb://store-tournamentmanager
          predicates:
            - Path=/tournaments/**

        - id: insper
          uri: https://www.insper.edu.br
          predicates:
            - Path=/

management:
  endpoints:
    web:
      base-path: /gateway/actuator
      exposure:
        include: [ 'prometheus' ]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

api:
  endpoints:
    open: >
      POST /auth/register,
      POST /auth/login,
      ANY /auth/actuator,
      ANY /accounts/actuator,
      ANY /winrecord/actuator,
      ANY /tournaments/actuator,
      ANY /gateway/actuator,
      ANY /auth/swagger**,
      ANY /accounts/swagger**,
      ANY /winrecord/swagger**,
      ANY /tournaments/swagger**,
      ANY /auth/v3**,
      ANY /accounts/v3**,
      ANY /winrecord/v3**,
      ANY /tournaments/v3**
